dist: trusty
sudo: required
language: ruby

rvm:
  - 2.5
  - 2.4
  - 2.3
  - ruby-head

env:
  global:
    - EXPECT_GPG_VERSION="2.2"
    - GPG_VERSION="latest"
    - RNP_VERSION="master"

    - DEPS_BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
    - BOTAN_PREFIX="${TRAVIS_BUILD_DIR}/opt/botan"
    - JSONC_PREFIX="${TRAVIS_BUILD_DIR}/opt/json-c"
    - RNP_PREFIX="${TRAVIS_BUILD_DIR}/opt/rnp"

    - LD_LIBRARY_PATH="${BOTAN_PREFIX}/lib:${JSONC_PREFIX}/lib:${RNP_PREFIX}/lib"

    - >
      GPG_CONFIGURE_OPTS="--disable-doc --enable-pinentry-curses
      --disable-pinentry-emacs --disable-pinentry-gtk2 --disable-pinentry-gnome3
      --disable-pinentry-qt --disable-pinentry-qt4 --disable-pinentry-qt5
      --disable-pinentry-tqt --disable-pinentry-fltk"

before_install:
  - pushd ci
  - >
    ./install_gpg_all.sh "${GPG_VERSION}"
    --build-dir "${DEPS_BUILD_DIR}/gpg"
    --configure-opts "${GPG_CONFIGURE_OPTS}"
    --folding-style travis
  - ./install_botan.sh
  - ./install_json_c.sh
  - ./install_rnp.sh
  - popd
  - gem install bundler -v 1.16.3

before_script:
  - bundle exec rake pgp_keys:generate
  - bundle exec rake pgp_keys:list

script:
  - bundle exec rspec --format documentation

matrix:
  allow_failures:
    - rvm: ruby-head
