os: osx
sudo: required
language: ruby

addons:
  homebrew:
    brewfile: ci/brewfile
    # update: true

rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - ruby-head

env:
  global:
    - EXPECT_GPG_VERSION="2.2"
    - GPG_VERSION="latest"
    - RNP_VERSION="master"

before_install:
  - ci/dependencies.sh
  - gem install bundler -v "~> 2.0"

before_script:
  - bundle exec rake pgp_keys:generate
  - bundle exec rake pgp_keys:list

script:
  - bundle exec rspec --format documentation --profile 200

matrix:
  include:
    - env: TEST_WITHOUT_RNP="1"
    - env: TEST_WITHOUT_GPGME="1"
    # Test against older GPG versions
    - env: GPG_VERSION="2.1" EXPECT_GPG_VERSION="2.1"

  allow_failures:
    - rvm: ruby-head
