dist: xenial
language: minimal

env:
  global:
    - GPG_VERSION="latest"
  matrix:
    - RUBY=2.6
    - RUBY=2.5
    - RUBY=2.4
    - RUBY=2.3
    - RUBY=ruby-head

before_script:
  - docker build -f ci/Dockerfile -t enmail:test --build-arg RUBY_VERSION=${RUBY} --build-arg GPG_VERSION=${GPG_VERSION} .

script:
  - docker run -it enmail:test

matrix:
  include:
    - env: TEST_WITHOUT_RNP="1"
    - env: TEST_WITHOUT_GPGME="1"
    # Test against older GPG versions
    - env: GPG_VERSION="2.1" EXPECT_GPG_VERSION="2.1"

  allow_failures:
    - env: RUBY=ruby-head
