dist: trusty
sudo: required
language: ruby

rvm:
  - 2.5
  - 2.4
  - 2.3
  - ruby-head

env:
  global:
    - EXPECT_GPG_VERSION="2.2"
    - GPG_VERSION="latest"
    - GPG_BUILD_DIR="$TRAVIS_BUILD_DIR/build_gpg"
    - >
      GPG_CONFIGURE_OPTS="--disable-doc --enable-pinentry-curses
      --disable-pinentry-emacs --disable-pinentry-gtk2 --disable-pinentry-gnome3
      --disable-pinentry-qt --disable-pinentry-qt4 --disable-pinentry-qt5
      --disable-pinentry-tqt --disable-pinentry-fltk"

    - RNP_VERSION="master"
    - LOCAL_BUILDS="$TRAVIS_BUILD_DIR/build_rnp"
    - BOTAN_INSTALL="$TRAVIS_BUILD_DIR/opt"
    - CMOCKA_INSTALL="$TRAVIS_BUILD_DIR/opt"
    - JSONC_INSTALL="$TRAVIS_BUILD_DIR/opt"
    - RNP_INSTALL="$TRAVIS_BUILD_DIR/opt"

    - LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/opt/lib"

before_install:
  - ./install_gpg_all.sh "$GPG_VERSION" --build-dir "$GPG_BUILD_DIR" --configure-opts "$GPG_CONFIGURE_OPTS" --folding-style travis
  - ./install_rnp.sh
  - gem install bundler -v 1.16.1

before_script:
  - rake generate_pgp_keys

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.3
